create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  subject text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  session_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists academic_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  title text not null,
  subject_name text,
  item_kind text not null check (item_kind in ('exam', 'project')),
  exam_type text,
  chapters text,
  importance text not null check (importance in ('critical', 'high', 'medium', 'low')),
  confidence_percent integer not null check (confidence_percent between 0 and 100),
  due_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists study_subjects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  priority text not null check (priority in ('critical', 'high', 'medium', 'low')),
  confidence_percent integer not null check (confidence_percent between 0 and 100),
  weekly_goal_minutes integer not null default 0 check (weekly_goal_minutes >= 0),
  notes text,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists study_chapter_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  chapter_id text not null,
  confidence_level integer not null default 3 check (confidence_level between 1 and 5),
  progress_status text not null default 'not_started' check (progress_status in ('not_started', 'studying', 'weak', 'complete')),
  is_finished boolean not null default false,
  past_study_minutes integer not null default 0 check (past_study_minutes >= 0),
  estimated_total_minutes integer,
  difficulty integer check (difficulty between 1 and 5),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, chapter_id)
);

create table if not exists academic_risk_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  code_module text not null default 'AAA',
  code_presentation text not null default '2014J',
  gender text not null default 'M',
  region text not null default 'Unknown',
  highest_education text not null default 'A Level or Equivalent',
  imd_band text not null default 'Unknown',
  age_band text not null default '0-35',
  disability text not null default 'N',
  num_of_prev_attempts numeric not null default 0 check (num_of_prev_attempts >= 0),
  studied_credits numeric not null default 60 check (studied_credits >= 0),
  date_registration numeric not null default -30,
  module_presentation_length numeric not null default 240 check (module_presentation_length >= 1),
  has_unregistered_by_cutoff numeric not null default 0 check (has_unregistered_by_cutoff in (0, 1)),
  assessment_submissions numeric not null default 0 check (assessment_submissions >= 0),
  assessment_score_mean numeric not null default 0 check (assessment_score_mean between 0 and 100),
  assessment_score_min numeric not null default 0 check (assessment_score_min between 0 and 100),
  assessment_score_max numeric not null default 0 check (assessment_score_max between 0 and 100),
  assessment_weight_sum numeric not null default 0 check (assessment_weight_sum >= 0),
  assessment_weighted_score_mean numeric not null default 0 check (assessment_weighted_score_mean between 0 and 100),
  assessment_late_count numeric not null default 0 check (assessment_late_count >= 0),
  assessment_days_before_due_mean numeric not null default 0,
  assessment_banked_count numeric not null default 0 check (assessment_banked_count >= 0),
  assessments_due_by_cutoff numeric not null default 0 check (assessments_due_by_cutoff >= 0),
  assessment_completion_ratio numeric not null default 0 check (assessment_completion_ratio between 0 and 1),
  vle_total_clicks numeric not null default 0 check (vle_total_clicks >= 0),
  vle_clicks_pre_course numeric not null default 0 check (vle_clicks_pre_course >= 0),
  vle_clicks_first_14 numeric not null default 0 check (vle_clicks_first_14 >= 0),
  vle_clicks_first_30 numeric not null default 0 check (vle_clicks_first_30 >= 0),
  vle_clicks_recent_14 numeric not null default 0 check (vle_clicks_recent_14 >= 0),
  vle_active_days numeric not null default 0 check (vle_active_days >= 0),
  vle_mean_clicks_active_day numeric not null default 0 check (vle_mean_clicks_active_day >= 0),
  vle_max_clicks_active_day numeric not null default 0 check (vle_max_clicks_active_day >= 0),
  vle_activity_forumng numeric not null default 0 check (vle_activity_forumng >= 0),
  vle_activity_homepage numeric not null default 0 check (vle_activity_homepage >= 0),
  vle_activity_oucontent numeric not null default 0 check (vle_activity_oucontent >= 0),
  vle_activity_page numeric not null default 0 check (vle_activity_page >= 0),
  vle_activity_quiz numeric not null default 0 check (vle_activity_quiz >= 0),
  vle_activity_resource numeric not null default 0 check (vle_activity_resource >= 0),
  vle_activity_subpage numeric not null default 0 check (vle_activity_subpage >= 0),
  vle_activity_url numeric not null default 0 check (vle_activity_url >= 0),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null default 'Student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table study_sessions
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table academic_items
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table academic_items
  add column if not exists chapters text;

alter table academic_items
  add column if not exists subject_name text;

alter table study_subjects
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table study_subjects
  add column if not exists notes text;

alter table study_chapter_progress
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table study_chapter_progress
  add column if not exists progress_status text not null default 'not_started';

alter table study_chapter_progress
  add column if not exists is_finished boolean not null default false;

alter table academic_risk_profiles
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

create index if not exists study_sessions_user_date_idx
  on study_sessions (user_id, session_date desc, created_at desc);

create index if not exists academic_items_user_due_idx
  on academic_items (user_id, due_date asc, created_at asc);

create index if not exists study_subjects_user_created_idx
  on study_subjects (user_id, created_at asc);

create unique index if not exists study_chapter_progress_user_chapter_idx
  on study_chapter_progress (user_id, chapter_id);

create unique index if not exists academic_risk_profiles_user_idx
  on academic_risk_profiles (user_id);

create index if not exists profiles_email_idx
  on profiles (email);

alter table study_sessions enable row level security;
alter table academic_items enable row level security;
alter table study_subjects enable row level security;
alter table study_chapter_progress enable row level security;
alter table academic_risk_profiles enable row level security;
alter table profiles enable row level security;

drop policy if exists "profiles_select_own" on profiles;
create policy "profiles_select_own"
on profiles for select
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on profiles;
create policy "profiles_insert_own"
on profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on profiles;
create policy "profiles_update_own"
on profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "study_sessions_select_own" on study_sessions;
create policy "study_sessions_select_own"
on study_sessions for select
using (auth.uid() = user_id);

drop policy if exists "study_sessions_insert_own" on study_sessions;
create policy "study_sessions_insert_own"
on study_sessions for insert
with check (auth.uid() = user_id);

drop policy if exists "study_sessions_update_own" on study_sessions;
create policy "study_sessions_update_own"
on study_sessions for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "study_sessions_delete_own" on study_sessions;
create policy "study_sessions_delete_own"
on study_sessions for delete
using (auth.uid() = user_id);

drop policy if exists "academic_items_select_own" on academic_items;
create policy "academic_items_select_own"
on academic_items for select
using (auth.uid() = user_id);

drop policy if exists "academic_items_insert_own" on academic_items;
create policy "academic_items_insert_own"
on academic_items for insert
with check (auth.uid() = user_id);

drop policy if exists "academic_items_update_own" on academic_items;
create policy "academic_items_update_own"
on academic_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "academic_items_delete_own" on academic_items;
create policy "academic_items_delete_own"
on academic_items for delete
using (auth.uid() = user_id);

drop policy if exists "study_subjects_select_own" on study_subjects;
create policy "study_subjects_select_own"
on study_subjects for select
using (auth.uid() = user_id);

drop policy if exists "study_subjects_insert_own" on study_subjects;
create policy "study_subjects_insert_own"
on study_subjects for insert
with check (auth.uid() = user_id);

drop policy if exists "study_subjects_update_own" on study_subjects;
create policy "study_subjects_update_own"
on study_subjects for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "study_subjects_delete_own" on study_subjects;
create policy "study_subjects_delete_own"
on study_subjects for delete
using (auth.uid() = user_id);

drop policy if exists "study_chapter_progress_select_own" on study_chapter_progress;
create policy "study_chapter_progress_select_own"
on study_chapter_progress for select
using (auth.uid() = user_id);

drop policy if exists "study_chapter_progress_insert_own" on study_chapter_progress;
create policy "study_chapter_progress_insert_own"
on study_chapter_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "study_chapter_progress_update_own" on study_chapter_progress;
create policy "study_chapter_progress_update_own"
on study_chapter_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "study_chapter_progress_delete_own" on study_chapter_progress;
create policy "study_chapter_progress_delete_own"
on study_chapter_progress for delete
using (auth.uid() = user_id);

drop policy if exists "academic_risk_profiles_select_own" on academic_risk_profiles;
create policy "academic_risk_profiles_select_own"
on academic_risk_profiles for select
using (auth.uid() = user_id);

drop policy if exists "academic_risk_profiles_insert_own" on academic_risk_profiles;
create policy "academic_risk_profiles_insert_own"
on academic_risk_profiles for insert
with check (auth.uid() = user_id);

drop policy if exists "academic_risk_profiles_update_own" on academic_risk_profiles;
create policy "academic_risk_profiles_update_own"
on academic_risk_profiles for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "academic_risk_profiles_delete_own" on academic_risk_profiles;
create policy "academic_risk_profiles_delete_own"
on academic_risk_profiles for delete
using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(coalesce(new.email, 'student'), '@', 1),
      'Student'
    )
  )
  on conflict (id) do update
  set
    email = excluded.email,
    display_name = excluded.display_name,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, email, display_name)
select
  id,
  coalesce(email, ''),
  coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'name', split_part(coalesce(email, 'student'), '@', 1), 'Student')
from auth.users
on conflict (id) do nothing;
