create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  subject text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  session_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists academic_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  title text not null,
  subject_name text,
  item_kind text not null check (item_kind in ('exam', 'project')),
  exam_type text,
  chapters text,
  importance text not null check (importance in ('critical', 'high', 'medium', 'low')),
  confidence_percent integer not null check (confidence_percent between 0 and 100),
  due_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists study_subjects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  priority text not null check (priority in ('critical', 'high', 'medium', 'low')),
  confidence_percent integer not null check (confidence_percent between 0 and 100),
  weekly_goal_minutes integer not null default 0 check (weekly_goal_minutes >= 0),
  notes text,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null default 'Student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table study_sessions
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table academic_items
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table academic_items
  add column if not exists chapters text;

alter table academic_items
  add column if not exists subject_name text;

alter table study_subjects
  add column if not exists user_id uuid references auth.users(id) on delete cascade default auth.uid();

alter table study_subjects
  add column if not exists notes text;

create index if not exists study_sessions_user_date_idx
  on study_sessions (user_id, session_date desc, created_at desc);

create index if not exists academic_items_user_due_idx
  on academic_items (user_id, due_date asc, created_at asc);

create index if not exists study_subjects_user_created_idx
  on study_subjects (user_id, created_at asc);

create index if not exists profiles_email_idx
  on profiles (email);

alter table study_sessions enable row level security;
alter table academic_items enable row level security;
alter table study_subjects enable row level security;
alter table profiles enable row level security;

drop policy if exists "profiles_select_own" on profiles;
create policy "profiles_select_own"
on profiles for select
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on profiles;
create policy "profiles_insert_own"
on profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on profiles;
create policy "profiles_update_own"
on profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "study_sessions_select_own" on study_sessions;
create policy "study_sessions_select_own"
on study_sessions for select
using (auth.uid() = user_id);

drop policy if exists "study_sessions_insert_own" on study_sessions;
create policy "study_sessions_insert_own"
on study_sessions for insert
with check (auth.uid() = user_id);

drop policy if exists "study_sessions_update_own" on study_sessions;
create policy "study_sessions_update_own"
on study_sessions for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "study_sessions_delete_own" on study_sessions;
create policy "study_sessions_delete_own"
on study_sessions for delete
using (auth.uid() = user_id);

drop policy if exists "academic_items_select_own" on academic_items;
create policy "academic_items_select_own"
on academic_items for select
using (auth.uid() = user_id);

drop policy if exists "academic_items_insert_own" on academic_items;
create policy "academic_items_insert_own"
on academic_items for insert
with check (auth.uid() = user_id);

drop policy if exists "academic_items_update_own" on academic_items;
create policy "academic_items_update_own"
on academic_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "academic_items_delete_own" on academic_items;
create policy "academic_items_delete_own"
on academic_items for delete
using (auth.uid() = user_id);

drop policy if exists "study_subjects_select_own" on study_subjects;
create policy "study_subjects_select_own"
on study_subjects for select
using (auth.uid() = user_id);

drop policy if exists "study_subjects_insert_own" on study_subjects;
create policy "study_subjects_insert_own"
on study_subjects for insert
with check (auth.uid() = user_id);

drop policy if exists "study_subjects_update_own" on study_subjects;
create policy "study_subjects_update_own"
on study_subjects for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "study_subjects_delete_own" on study_subjects;
create policy "study_subjects_delete_own"
on study_subjects for delete
using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(coalesce(new.email, 'student'), '@', 1),
      'Student'
    )
  )
  on conflict (id) do update
  set
    email = excluded.email,
    display_name = excluded.display_name,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, email, display_name)
select
  id,
  coalesce(email, ''),
  coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'name', split_part(coalesce(email, 'student'), '@', 1), 'Student')
from auth.users
on conflict (id) do nothing;
