create table if not exists study_sessions (
  id bigint generated by default as identity primary key,
  subject text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  session_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists academic_items (
  id bigint generated by default as identity primary key,
  title text not null,
  item_kind text not null check (item_kind in ('exam', 'project')),
  exam_type text,
  importance text not null check (importance in ('critical', 'high', 'medium', 'low')),
  confidence_percent integer not null check (confidence_percent between 0 and 100),
  due_date date not null,
  created_at timestamptz not null default now()
);

create index if not exists study_sessions_session_date_idx
  on study_sessions (session_date desc, created_at desc);

create index if not exists academic_items_due_date_idx
  on academic_items (due_date asc, created_at asc);
